// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"time"
)

type Destination struct {
	ID         int32
	SourceID   int32
	SourceName string
	Value      string
	AddedAt    time.Time
}

type Primary struct {
	ID    int32
	Name  string
	Value string
}

type Secondary struct {
	ID    int32
	Name  string
	Value string
}

type Tertiary struct {
	ID    int32
	Name  string
	Value string
}
