// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"database/sql"
)

type Primary struct {
	ID    int32
	Value sql.NullString
}

type Secondary struct {
	ID    int32
	Value sql.NullString
}

type Tertiary struct {
	ID    int32
	Value sql.NullString
}
