// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const createPrimary = `-- name: CreatePrimary :execresult
INSERT INTO ` + "`" + `primary` + "`" + ` (` + "`" + `value` + "`" + `)
VALUES (?)
`

func (q *Queries) CreatePrimary(ctx context.Context, value sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrimary, value)
}

const createSecondary = `-- name: CreateSecondary :execresult
INSERT INTO ` + "`" + `secondary` + "`" + ` (` + "`" + `value` + "`" + `)
VALUES (?)
`

func (q *Queries) CreateSecondary(ctx context.Context, value sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSecondary, value)
}

const createTertiary = `-- name: CreateTertiary :execresult
INSERT INTO ` + "`" + `tertiary` + "`" + ` (` + "`" + `value` + "`" + `)
VALUES (?)
`

func (q *Queries) CreateTertiary(ctx context.Context, value sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTertiary, value)
}
