version: "3.9"

services:
  consumer-secondary:
    build:
      context: ../
      dockerfile: Dockerfile
      target: final
    image: ${IMAGE_BASE_NAME}-go:latest
    container_name: ${BASE_NAME}-consumer-secondary
    depends_on:
      - localstack
      - elasticsearch
    volumes:
      - "../config/secondary.json:/opt/app/config.json"
    entrypoint: "/entrypoint.sh"
    command: --config=config.json --module=consumer --threads=${CONSUMER_THREADS} --wait=${CONSUMER_WAIT}

networks:
  default:
    name: ${NETWORK}
