version: "3.9"

services:
  maxwell-primary:
    build:
      context: ../maxwell
      dockerfile: Dockerfile
    image: ${IMAGE_BASE_NAME}-maxwell:latest
    container_name: ${BASE_NAME}-maxwell-primary
    #depends_on:
    #  - mariadb
    #  - localstack
    environment:
      - "HOST=${BASE_NAME}-mariadb"
      - "PORT=3306"
      - "USERNAME=maxwell"
      - "PASSWORD=password"
      - "PRODUCER=sqs"
      - "REPLICA_SERVER_ID=1"
      - "SERVER_ID=primary"
      - "FILTER=exclude:*.*,include:example.primary"
      - "ENDPOINT_URL=http://${BASE_NAME}-localstack:4566"
      - "SQS_QUEUE_URI=http://${BASE_NAME}-localstack:4566/000000000000/maxwell-primary"
      # For aws cli
      - "AWS_ACCESS_KEY_ID=dummy"
      - "AWS_SECRET_ACCESS_KEY=dummy"
      - "AWS_REGION=eu-west-1"

networks:
  default:
    name: ${NETWORK}
