version: "3.9"

services:
  maxwell-tertiary:
    build:
      context: ../maxwell
      dockerfile: Dockerfile
    image: ${IMAGE_BASE_NAME}-maxwell:latest
    container_name: ${BASE_NAME}-maxwell-tertiary
    depends_on:
      - mariadb
      - localstack
    environment:
      - "HOST=${BASE_NAME}-mariadb"
      - "PORT=3306"
      - "USERNAME=maxwell"
      - "PASSWORD=password"
      - "PRODUCER=sqs"
      - "IGNORE_PRODUCER_ERROR=false" # not sure if this actually has any effect... `config.properties` was edited too...
      - "REPLICA_SERVER_ID=3"
      - "SERVER_ID=tertiary"
      - "FILTER=exclude:*.*,include:example.tertiary"
      - "ENDPOINT_URL=http://${BASE_NAME}-localstack:4566"
      - "SQS_QUEUE_URI=http://${BASE_NAME}-localstack:4566/000000000000/maxwell-tertiary"
      - "JAVASCRIPT_FILE=js/filter.js"
      # For aws cli
      - "AWS_ACCESS_KEY_ID=dummy"
      - "AWS_SECRET_ACCESS_KEY=dummy"
      - "AWS_REGION=eu-west-1"
    volumes:
      - "../js/filter.js:/app/js/filter.js"
    restart: on-failure

networks:
  default:
    name: ${NETWORK}
